version: '2'

volumes:
  nextcloud:
  nextcloud-db:

services:
  nextcloud-db:
    image: mysql:8
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=N3xtCl0ud!
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:stable-apache
    ports:
      - 8081:80
    links:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
    restart: always
