version: '2'

networks:
  nclan:

services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - /var/mtigas-custom/nextcloud/db:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=en_US.UTF8"

  app:
    image: nextcloud:stable-apache
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - /var/mtigas-custom/nextcloud/app:/var/www/html
    restart: always
