version: '2'

services:
  nextcloud-db:
    image: postgres:11
    restart: always
    volumes:
      - /var/mtigas-custom/nextcloud/db:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DATABASE=nextcloud
      - POSTGRES_USER=nextcloud

  app:
    image: nextcloud:stable-apache
    ports:
      - 8081:80
    links:
      - nextcloud-db
    volumes:
      - /var/mtigas-custom/nextcloud/app:/var/www/html
    restart: always
